-- Preserve intentionally unscheduled leagues instead of storing a synthetic draft start.
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;

CREATE TABLE "new_LeagueSettings" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "rosterSize" INTEGER NOT NULL,
    "benchSize" INTEGER NOT NULL,
    "maxTeams" INTEGER NOT NULL,
    "pickSeconds" INTEGER NOT NULL,
    "allowAutoPick" BOOLEAN NOT NULL DEFAULT true,
    "positionLimitsJson" TEXT,
    "autoPickRulesJson" TEXT,
    "draftType" TEXT NOT NULL,
    "pickOrder" TEXT NOT NULL DEFAULT 'RANDOM',
    "waiverRule" TEXT NOT NULL DEFAULT 'WEEKLY',
    "startAt" DATETIME,
    "timeZone" TEXT NOT NULL DEFAULT 'UTC',
    "locked" BOOLEAN NOT NULL DEFAULT false,
    "scoringMode" TEXT NOT NULL DEFAULT 'H2H_EACH_CATEGORY',
    "fixtureGenerationMode" TEXT NOT NULL DEFAULT 'AUTOMATIC',
    "lineupSlotsJson" TEXT,
    "categoryDirectionsJson" TEXT,
    "scoringSettingsLockedAt" DATETIME,
    "competitionStatus" TEXT NOT NULL DEFAULT 'SETUP',
    "competitionRulesJson" TEXT,
    "competitionRulesVersion" INTEGER NOT NULL DEFAULT 0,
    "competitionPublishedAt" DATETIME,
    "tradeLimit" INTEGER NOT NULL DEFAULT 10,
    "tradeReviewMode" TEXT NOT NULL DEFAULT 'NONE',
    "tradeDeadline" DATETIME,
    "tradeOfferExpiryHours" INTEGER NOT NULL DEFAULT 72,
    "tradeReviewHours" INTEGER NOT NULL DEFAULT 24,
    "tradeVetoThreshold" INTEGER NOT NULL DEFAULT 3,
    "enableCaptainSystem" BOOLEAN NOT NULL DEFAULT false,
    "captainMultiplier" REAL NOT NULL DEFAULT 2.0,
    "viceCaptainMultiplier" REAL NOT NULL DEFAULT 1.5
);

INSERT INTO "new_LeagueSettings" (
    "allowAutoPick",
    "autoPickRulesJson",
    "benchSize",
    "captainMultiplier",
    "categoryDirectionsJson",
    "competitionPublishedAt",
    "competitionRulesJson",
    "competitionRulesVersion",
    "competitionStatus",
    "draftType",
    "enableCaptainSystem",
    "fixtureGenerationMode",
    "id",
    "lineupSlotsJson",
    "locked",
    "maxTeams",
    "pickOrder",
    "pickSeconds",
    "positionLimitsJson",
    "rosterSize",
    "scoringMode",
    "scoringSettingsLockedAt",
    "startAt",
    "timeZone",
    "tradeDeadline",
    "tradeLimit",
    "tradeOfferExpiryHours",
    "tradeReviewHours",
    "tradeReviewMode",
    "tradeVetoThreshold",
    "viceCaptainMultiplier",
    "waiverRule"
)
SELECT
    "allowAutoPick",
    "autoPickRulesJson",
    "benchSize",
    "captainMultiplier",
    "categoryDirectionsJson",
    "competitionPublishedAt",
    "competitionRulesJson",
    "competitionRulesVersion",
    "competitionStatus",
    "draftType",
    "enableCaptainSystem",
    "fixtureGenerationMode",
    "id",
    "lineupSlotsJson",
    "locked",
    "maxTeams",
    "pickOrder",
    "pickSeconds",
    "positionLimitsJson",
    "rosterSize",
    "scoringMode",
    "scoringSettingsLockedAt",
    "startAt",
    "timeZone",
    "tradeDeadline",
    "tradeLimit",
    "tradeOfferExpiryHours",
    "tradeReviewHours",
    "tradeReviewMode",
    "tradeVetoThreshold",
    "viceCaptainMultiplier",
    "waiverRule"
FROM "LeagueSettings";

DROP TABLE "LeagueSettings";
ALTER TABLE "new_LeagueSettings" RENAME TO "LeagueSettings";

PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
