-- Replayed histories can encounter this migration before DraftEvent exists.
-- The locked claim fields are created as part of the DraftEvent bootstrap
-- migration so fresh shadow databases can apply the chain from zero safely.
