extend type FantasyTeam {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID!
    @default(expr: "uuidV4()")
    @fdc_generated(from: "FantasyTeam", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `FantasyTeam`.`league`. It must match the value of `League`.`id`. See `@ref` for how to customize it.
  """
  leagueId: UUID! @fdc_generated(from: "FantasyTeam.league", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `FantasyTeam`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "FantasyTeam.user", purpose: IMPLICIT_REF_FIELD)
}
extend type League {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "League", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `League`.`adminUser`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  adminUserId: UUID! @fdc_generated(from: "League.adminUser", purpose: IMPLICIT_REF_FIELD)
}
extend type MatchEvent {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID!
    @default(expr: "uuidV4()")
    @fdc_generated(from: "MatchEvent", purpose: IMPLICIT_KEY_FIELD)
}
extend type Player {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Player", purpose: IMPLICIT_KEY_FIELD)
}
extend type PlayerPerformance {
  """
  ✨ Implicit foreign key field based on `PlayerPerformance`.`player`. It must match the value of `Player`.`id`. See `@ref` for how to customize it.
  """
  playerId: UUID! @fdc_generated(from: "PlayerPerformance.player", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `PlayerPerformance`.`matchEvent`. It must match the value of `MatchEvent`.`id`. See `@ref` for how to customize it.
  """
  matchEventId: UUID!
    @fdc_generated(from: "PlayerPerformance.matchEvent", purpose: IMPLICIT_REF_FIELD)
}
extend type RosterSpot {
  """
  ✨ Implicit foreign key field based on `RosterSpot`.`fantasyTeam`. It must match the value of `FantasyTeam`.`id`. See `@ref` for how to customize it.
  """
  fantasyTeamId: UUID! @fdc_generated(from: "RosterSpot.fantasyTeam", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `RosterSpot`.`player`. It must match the value of `Player`.`id`. See `@ref` for how to customize it.
  """
  playerId: UUID! @fdc_generated(from: "RosterSpot.player", purpose: IMPLICIT_REF_FIELD)
}
extend type User {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "User", purpose: IMPLICIT_KEY_FIELD)
}
