extend type Mutation {
  """
  ✨ Insert a single `FantasyTeam` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  fantasyTeam_insert(
    """
    Data object to insert into the table.
    """
    data: FantasyTeam_Data!
  ): FantasyTeam_KeyOutput! @fdc_generated(from: "FantasyTeam", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `League` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  league_insert(
    """
    Data object to insert into the table.
    """
    data: League_Data!
  ): League_KeyOutput! @fdc_generated(from: "League", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `MatchEvent` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  matchEvent_insert(
    """
    Data object to insert into the table.
    """
    data: MatchEvent_Data!
  ): MatchEvent_KeyOutput! @fdc_generated(from: "MatchEvent", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Player` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  player_insert(
    """
    Data object to insert into the table.
    """
    data: Player_Data!
  ): Player_KeyOutput! @fdc_generated(from: "Player", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `PlayerPerformance` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  playerPerformance_insert(
    """
    Data object to insert into the table.
    """
    data: PlayerPerformance_Data!
  ): PlayerPerformance_KeyOutput! @fdc_generated(from: "PlayerPerformance", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `RosterSpot` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  rosterSpot_insert(
    """
    Data object to insert into the table.
    """
    data: RosterSpot_Data!
  ): RosterSpot_KeyOutput! @fdc_generated(from: "RosterSpot", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `User` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insert(
    """
    Data object to insert into the table.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: INSERT_SINGLE)
  """
  ✨ Insert `FantasyTeam` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  fantasyTeam_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [FantasyTeam_Data!]!
  ): [FantasyTeam_KeyOutput!]! @fdc_generated(from: "FantasyTeam", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `League` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  league_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [League_Data!]!
  ): [League_KeyOutput!]! @fdc_generated(from: "League", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `MatchEvent` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  matchEvent_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [MatchEvent_Data!]!
  ): [MatchEvent_KeyOutput!]! @fdc_generated(from: "MatchEvent", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Player` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  player_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Player_Data!]!
  ): [Player_KeyOutput!]! @fdc_generated(from: "Player", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `PlayerPerformance` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  playerPerformance_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [PlayerPerformance_Data!]!
  ): [PlayerPerformance_KeyOutput!]!
    @fdc_generated(from: "PlayerPerformance", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `RosterSpot` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  rosterSpot_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [RosterSpot_Data!]!
  ): [RosterSpot_KeyOutput!]! @fdc_generated(from: "RosterSpot", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `User` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `FantasyTeam` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `FantasyTeam`.
  """
  fantasyTeam_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: FantasyTeam_Data!
  ): FantasyTeam_KeyOutput! @fdc_generated(from: "FantasyTeam", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `League` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `League`.
  """
  league_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: League_Data!
  ): League_KeyOutput! @fdc_generated(from: "League", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `MatchEvent` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `MatchEvent`.
  """
  matchEvent_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: MatchEvent_Data!
  ): MatchEvent_KeyOutput! @fdc_generated(from: "MatchEvent", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Player` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Player`.
  """
  player_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Player_Data!
  ): Player_KeyOutput! @fdc_generated(from: "Player", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `PlayerPerformance` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `PlayerPerformance`.
  """
  playerPerformance_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: PlayerPerformance_Data!
  ): PlayerPerformance_KeyOutput! @fdc_generated(from: "PlayerPerformance", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `RosterSpot` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `RosterSpot`.
  """
  rosterSpot_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: RosterSpot_Data!
  ): RosterSpot_KeyOutput! @fdc_generated(from: "RosterSpot", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `User` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `FantasyTeam` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `FantasyTeam`.
  """
  fantasyTeam_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [FantasyTeam_Data!]!
  ): [FantasyTeam_KeyOutput!]! @fdc_generated(from: "FantasyTeam", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `League` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `League`.
  """
  league_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [League_Data!]!
  ): [League_KeyOutput!]! @fdc_generated(from: "League", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `MatchEvent` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `MatchEvent`.
  """
  matchEvent_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [MatchEvent_Data!]!
  ): [MatchEvent_KeyOutput!]! @fdc_generated(from: "MatchEvent", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Player` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Player`.
  """
  player_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Player_Data!]!
  ): [Player_KeyOutput!]! @fdc_generated(from: "Player", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `PlayerPerformance` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `PlayerPerformance`.
  """
  playerPerformance_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [PlayerPerformance_Data!]!
  ): [PlayerPerformance_KeyOutput!]!
    @fdc_generated(from: "PlayerPerformance", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `RosterSpot` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `RosterSpot`.
  """
  rosterSpot_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [RosterSpot_Data!]!
  ): [RosterSpot_KeyOutput!]! @fdc_generated(from: "RosterSpot", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `User` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `FantasyTeam` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `FantasyTeam` or `null` if not found.
  """
  fantasyTeam_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: FantasyTeam_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: FantasyTeam_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: FantasyTeam_Data!
  ): FantasyTeam_KeyOutput @fdc_generated(from: "FantasyTeam", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `League` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `League` or `null` if not found.
  """
  league_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: League_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: League_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: League_Data!
  ): League_KeyOutput @fdc_generated(from: "League", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `MatchEvent` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `MatchEvent` or `null` if not found.
  """
  matchEvent_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: MatchEvent_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: MatchEvent_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: MatchEvent_Data!
  ): MatchEvent_KeyOutput @fdc_generated(from: "MatchEvent", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Player` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Player` or `null` if not found.
  """
  player_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Player_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Player_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Player_Data!
  ): Player_KeyOutput @fdc_generated(from: "Player", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `PlayerPerformance` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `PlayerPerformance` or `null` if not found.
  """
  playerPerformance_update(
    """
    The key used to identify the object.
    """
    key: PlayerPerformance_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: PlayerPerformance_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: PlayerPerformance_Data!
  ): PlayerPerformance_KeyOutput @fdc_generated(from: "PlayerPerformance", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `RosterSpot` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `RosterSpot` or `null` if not found.
  """
  rosterSpot_update(
    """
    The key used to identify the object.
    """
    key: RosterSpot_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: RosterSpot_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: RosterSpot_Data!
  ): RosterSpot_KeyOutput @fdc_generated(from: "RosterSpot", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `User` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `User` or `null` if not found.
  """
  user_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: User_Data!
  ): User_KeyOutput @fdc_generated(from: "User", purpose: UPDATE_SINGLE)
  """
  ✨ Update `FantasyTeam` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  fantasyTeam_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: FantasyTeam_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: FantasyTeam_Data!
  ): Int! @fdc_generated(from: "FantasyTeam", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `League` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  league_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: League_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: League_Data!
  ): Int! @fdc_generated(from: "League", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `MatchEvent` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  matchEvent_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: MatchEvent_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: MatchEvent_Data!
  ): Int! @fdc_generated(from: "MatchEvent", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Player` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  player_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Player_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Player_Data!
  ): Int! @fdc_generated(from: "Player", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `PlayerPerformance` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  playerPerformance_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: PlayerPerformance_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: PlayerPerformance_Data!
  ): Int! @fdc_generated(from: "PlayerPerformance", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `RosterSpot` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  rosterSpot_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: RosterSpot_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: RosterSpot_Data!
  ): Int! @fdc_generated(from: "RosterSpot", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `User` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  user_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: User_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: User_Data!
  ): Int! @fdc_generated(from: "User", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `FantasyTeam` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  fantasyTeam_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: FantasyTeam_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: FantasyTeam_FirstRow
  ): FantasyTeam_KeyOutput @fdc_generated(from: "FantasyTeam", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `League` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  league_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: League_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: League_FirstRow
  ): League_KeyOutput @fdc_generated(from: "League", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `MatchEvent` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  matchEvent_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: MatchEvent_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: MatchEvent_FirstRow
  ): MatchEvent_KeyOutput @fdc_generated(from: "MatchEvent", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Player` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  player_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Player_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Player_FirstRow
  ): Player_KeyOutput @fdc_generated(from: "Player", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `PlayerPerformance` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  playerPerformance_delete(
    """
    The key used to identify the object.
    """
    key: PlayerPerformance_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: PlayerPerformance_FirstRow
  ): PlayerPerformance_KeyOutput @fdc_generated(from: "PlayerPerformance", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `RosterSpot` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  rosterSpot_delete(
    """
    The key used to identify the object.
    """
    key: RosterSpot_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: RosterSpot_FirstRow
  ): RosterSpot_KeyOutput @fdc_generated(from: "RosterSpot", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `User` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  user_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User_KeyOutput @fdc_generated(from: "User", purpose: DELETE_SINGLE)
  """
  ✨ Delete `FantasyTeam` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  fantasyTeam_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: FantasyTeam_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "FantasyTeam", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `League` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  league_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: League_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "League", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `MatchEvent` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  matchEvent_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: MatchEvent_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "MatchEvent", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Player` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  player_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Player_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Player", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `PlayerPerformance` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  playerPerformance_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: PlayerPerformance_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "PlayerPerformance", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `RosterSpot` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  rosterSpot_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: RosterSpot_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "RosterSpot", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `User` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  user_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: User_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "User", purpose: DELETE_MULTIPLE)
}
