extend type Query {
  """
  ✨ Look up a single `FantasyTeam` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  fantasyTeam(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: FantasyTeam_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: FantasyTeam_FirstRow
  ): FantasyTeam @fdc_generated(from: "FantasyTeam", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `League` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  league(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: League_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: League_FirstRow
  ): League @fdc_generated(from: "League", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `MatchEvent` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  matchEvent(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: MatchEvent_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: MatchEvent_FirstRow
  ): MatchEvent @fdc_generated(from: "MatchEvent", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Player` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  player(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Player_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Player_FirstRow
  ): Player @fdc_generated(from: "Player", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `PlayerPerformance` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  playerPerformance(
    """
    The key used to identify the object.
    """
    key: PlayerPerformance_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: PlayerPerformance_FirstRow
  ): PlayerPerformance @fdc_generated(from: "PlayerPerformance", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `RosterSpot` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  rosterSpot(
    """
    The key used to identify the object.
    """
    key: RosterSpot_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: RosterSpot_FirstRow
  ): RosterSpot @fdc_generated(from: "RosterSpot", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `User` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  user(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User @fdc_generated(from: "User", purpose: QUERY_SINGLE)
  """
  ✨ List `FantasyTeam` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  fantasyTeams(
    """
    Filter condition to narrow down the query results.
    """
    where: FantasyTeam_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [FantasyTeam_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: FantasyTeam_Having
  ): [FantasyTeam!]! @fdc_generated(from: "FantasyTeam", purpose: QUERY_MULTIPLE)
  """
  ✨ List `League` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  leagues(
    """
    Filter condition to narrow down the query results.
    """
    where: League_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [League_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: League_Having
  ): [League!]! @fdc_generated(from: "League", purpose: QUERY_MULTIPLE)
  """
  ✨ List `MatchEvent` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  matchEvents(
    """
    Filter condition to narrow down the query results.
    """
    where: MatchEvent_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [MatchEvent_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: MatchEvent_Having
  ): [MatchEvent!]! @fdc_generated(from: "MatchEvent", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Player` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  players(
    """
    Filter condition to narrow down the query results.
    """
    where: Player_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Player_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Player_Having
  ): [Player!]! @fdc_generated(from: "Player", purpose: QUERY_MULTIPLE)
  """
  ✨ List `PlayerPerformance` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  playerPerformances(
    """
    Filter condition to narrow down the query results.
    """
    where: PlayerPerformance_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [PlayerPerformance_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: PlayerPerformance_Having
  ): [PlayerPerformance!]! @fdc_generated(from: "PlayerPerformance", purpose: QUERY_MULTIPLE)
  """
  ✨ List `RosterSpot` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  rosterSpots(
    """
    Filter condition to narrow down the query results.
    """
    where: RosterSpot_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [RosterSpot_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: RosterSpot_Having
  ): [RosterSpot!]! @fdc_generated(from: "RosterSpot", purpose: QUERY_MULTIPLE)
  """
  ✨ List `User` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  users(
    """
    Filter condition to narrow down the query results.
    """
    where: User_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [User_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: User_Having
  ): [User!]! @fdc_generated(from: "User", purpose: QUERY_MULTIPLE)
}
