-- Tell the planner what the retained-sources check costs, so the event currency checks call it once.
--
-- outcome_acquisition_promoted_event_current and outcome_acquisition_arrival_event_current filter the
-- promotion's candidate with outcome_external_candidate_retained_sources_current(candidate, cutoff),
-- which re-validates every retained source of the candidate. The function was declared with the
-- default cost (100), so the planner saw no harm in evaluating it inside a loop driven from the review
-- decisions: in the reviewed subset promotion suite it ran for every finalized candidate on every
-- loop (about 415 times for one currency check), and one spell registration took 18-19 s, which
-- pushed three cases past their 120 s limit on CI. Declaring its real cost makes the planner apply it
-- to the promotion's own candidate only. No behaviour changes: the same rows qualify.
ALTER FUNCTION outcome_external_candidate_retained_sources_current(text, timestamp with time zone) COST 10000;
