import { readFileSync } from 'node:fs';
import { join } from 'node:path';

import { describe, expect, it } from 'vitest';

function readRepoFile(path: string): string {
  return readFileSync(join(process.cwd(), path), 'utf8');
}

describe('league matchups UI architecture', () => {
  it('adds service-backed league matchups, lineup, standings, and scoring settings surfaces', () => {
    const leagueTabs = readRepoFile('src/components/league/LeagueTabs.tsx');
    const matchupsPanel = readRepoFile('src/components/league/matchups/LeagueMatchupsPanel.tsx');
    const lineupPanel = readRepoFile('src/components/league/matchups/LeagueLineupPanel.tsx');
    const lineupRosterPool = readRepoFile('src/components/league/matchups/LineupRosterPool.tsx');
    const lineupFieldBoard = readRepoFile('src/components/league/matchups/LineupFieldBoard.tsx');
    const standingsPanel = readRepoFile('src/components/league/matchups/LeagueStandingsPanel.tsx');
    const scoringSettings = readRepoFile('src/components/league/settings/ScoringSettingsPanel.tsx');

    expect(leagueTabs).toContain("'matchups'");
    expect(leagueTabs).toContain("'lineup'");
    expect(leagueTabs).toContain("'standings'");
    expect(leagueTabs).toContain('LeagueMatchupsPanel');
    expect(leagueTabs).toContain('LeagueLineupPanel');
    expect(leagueTabs).toContain('LeagueStandingsPanel');
    expect(leagueTabs).toContain('ScoringSettingsPanel');

    expect(matchupsPanel).toContain('/api/leagues/${leagueId}/matchups');
    expect(matchupsPanel).not.toContain('Generate fixtures');
    expect(matchupsPanel).toContain('?round=');
    expect(matchupsPanel).toContain('Weekly head-to-head Match Centre');
    expect(matchupsPanel).toContain('categoryRows');
    expect(matchupsPanel).toContain('MatchupHeadToHeadCard');
    expect(matchupsPanel).toContain('CategoryTotalsGrid');
    expect(matchupsPanel).toContain('MirroredPlayerMatchupTable');
    expect(matchupsPanel).toContain('Today&apos;s Stats');
    expect(matchupsPanel).toContain('Match-up totals by scoring category');
    expect(matchupsPanel).toContain('table-fixed');
    expect(matchupsPanel).toContain('MATCH_CENTRE_PLAYER_COLUMN_WIDTH');
    expect(matchupsPanel).toContain('Mirrored player contribution table');
    expect(matchupsPanel).not.toContain('Statly Z');
    expect(matchupsPanel).toContain('Round');
    expect(matchupsPanel).not.toContain('/recalculate');
    expect(matchupsPanel).not.toContain('Finalize');
    expect(matchupsPanel).not.toContain('Recalculate');
    expect(matchupsPanel).toContain('No weekly matchups are available yet');
    expect(matchupsPanel).toContain('Set your lineup');
    expect(matchupsPanel).toContain('Open the My Lineup tab');
    expect(lineupPanel).toContain('/api/leagues/${leagueId}/lineups/${round}');
    expect(lineupPanel).toContain('rosterPlayers');
    expect(lineupPanel).toContain('lineupSlots');
    expect(lineupPanel).toContain('LineupFieldBoard');
    expect(lineupPanel).toContain('availablePlayers={availableRosterPlayers}');
    expect(lineupPanel).toContain('assignPlayerToSpot');
    expect(lineupPanel).toContain('removePlayerFromSlot');
    expect(lineupPanel).not.toContain('canAssignToSlot');
    expect(lineupPanel).not.toContain('xl:grid-cols-[300px_minmax(0,1fr)]');
    expect(lineupPanel).toContain("method: 'PATCH'");
    expect(lineupRosterPool).toContain('draggable');
    expect(lineupRosterPool).toContain('setDragPlayer');
    expect(lineupRosterPool).toContain('onSelectPlayer');
    expect(lineupRosterPool).toContain('Available players');
    expect(lineupRosterPool).toContain('Unassigned roster pool');
    expect(lineupRosterPool).not.toContain('Sideline roster pool');
    expect(lineupRosterPool).toContain('uppercase text-[color:var(--league-text)]');
    expect(lineupRosterPool).toContain("variant?: 'default' | 'stadium'");
    expect(lineupRosterPool).toContain('embedded?: boolean');
    expect(lineupRosterPool).toContain('isEmbeddedStadium');
    expect(lineupRosterPool).toContain('rounded-full');
    expect(lineupRosterPool).toContain('isStadium ? null');
    expect(lineupRosterPool).not.toContain('canAssignToSlot');
    expect(lineupFieldBoard).toContain('AFL field lineup builder');
    expect(lineupFieldBoard).not.toContain("import Image from 'next/image'");
    expect(lineupFieldBoard).not.toContain('/Assets/statly-stadium-hero.png');
    expect(lineupFieldBoard).toContain('LineupRosterPool');
    expect(lineupFieldBoard).toContain('variant="stadium"');
    expect(lineupFieldBoard).toContain('embedded');
    expect(lineupFieldBoard).toContain("if (typedSlot === 'UTIL') return null");
    expect(lineupFieldBoard).toContain('availablePlayers');
    expect(lineupFieldBoard).toContain('SLOT_FIELD_BANDS');
    expect(lineupFieldBoard).toContain('SLOT_BAND_GRIDS');
    expect(lineupFieldBoard).toContain('Field builder');
    expect(lineupFieldBoard).toContain('Interchange');
    expect(lineupFieldBoard).toContain('min-h-[1120px]');
    expect(lineupFieldBoard).toContain("url('/Assets/afl-turf-texture.png')");
    expect(lineupFieldBoard).toContain('rounded-[999px]');
    expect(lineupFieldBoard).toContain('overflow-hidden');
    expect(lineupFieldBoard).toContain('lg:grid-cols-[minmax(240px,0.8fr)');
    expect(lineupFieldBoard).toContain('grid-cols-[repeat(auto-fit,minmax(156px,1fr))]');
    expect(lineupRosterPool).toContain('px-0 pb-3 pt-0');
    expect(lineupRosterPool).toContain("isEmbeddedStadium ? 'px-0 py-3' : 'p-2'");
    expect(lineupRosterPool).toContain(
      "isEmbeddedStadium ? 'grid gap-3 lg:grid-cols-3' : 'space-y-2'"
    );
    expect(lineupFieldBoard).not.toContain('className="p-3"');
    expect(lineupFieldBoard).not.toContain('bg-slate-950/64 p-3');
    expect(lineupFieldBoard).toContain('interchangeSpots');
    expect(lineupFieldBoard).toContain('Lineup sideline');
    expect(lineupFieldBoard).toContain('variant="interchange"');
    expect(lineupFieldBoard).not.toContain('border-red-700');
    expect(lineupFieldBoard).not.toContain('bg-slate');
    expect(lineupRosterPool).not.toContain('text-cyan');
    expect(lineupFieldBoard).toContain('radial-gradient');
    expect(lineupFieldBoard).toContain('lg:grid-cols-1');
    expect(lineupFieldBoard).toContain('onDrop');
    expect(lineupFieldBoard).toContain('getDragPlayerId');
    expect(lineupFieldBoard).toContain('selectedPlayerId');
    expect(lineupFieldBoard).toContain('Assign selected player');
    expect(lineupFieldBoard).toContain('Clear');
    expect(lineupFieldBoard).not.toContain('min-h-24');
    expect(lineupFieldBoard).toContain('FWD');
    expect(lineupFieldBoard).toContain('MID');
    expect(lineupFieldBoard).toContain('DEF');
    expect(lineupFieldBoard).toContain('RUC');
    expect(lineupFieldBoard).toContain('UTIL');
    expect(standingsPanel).toContain('Category record');
    expect(scoringSettings).toContain('H2H Each Category');
    expect(scoringSettings).toContain('H2H Most Categories');
    expect(scoringSettings).toContain('categoryDirections');
    expect(scoringSettings).toContain('lineupSlots');
  });
});
